// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wmsfo.Api.Data;

#nullable disable

namespace Wmsfo.Api.Data.Migrations
{
    [DbContext(typeof(WmsfoDbContext))]
    [Migration("20260911224158_A26ApiKey")]
    partial class A26ApiKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Wmsfo.Api.Data.AlertDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<long>("OutboxId")
                        .HasColumnType("bigint")
                        .HasColumnName("outbox_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("SesMessageId")
                        .HasColumnType("text")
                        .HasColumnName("ses_message_id");

                    b.Property<long>("SubscriberId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscriber_id");

                    b.HasKey("Id")
                        .HasName("alert_delivery_pkey");

                    b.HasAlternateKey("SubscriberId", "OutboxId")
                        .HasName("alert_delivery_subscriber_id_outbox_id_key");

                    b.HasIndex("Id")
                        .HasDatabaseName("alert_delivery_unsent")
                        .HasFilter("sent_at is null");

                    b.HasIndex("OutboxId")
                        .HasDatabaseName("alert_delivery_outbox");

                    b.ToTable("alert_delivery", null, t =>
                        {
                            t.HasComment("One email per (subscriber, outbox row). The unique constraint is what makes overlapping leaders safe.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.ApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllCapabilities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("all_capabilities");

                    b.PrimitiveCollection<string[]>("Capabilities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at")
                        .HasComment("Null (never) or rfc3339. Past it the key answers 401 unauthenticated.");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash")
                        .HasComment("sha256 of the plaintext key, 32 bytes. The plaintext is never stored.");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_prefix")
                        .HasComment("First 12 characters of the key, for display.");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at")
                        .HasComment("Set once by revoke. A revoked key never authenticates again.");

                    b.HasKey("Id")
                        .HasName("api_key_pkey");

                    b.HasAlternateKey("KeyHash")
                        .HasName("api_key_key_hash_key");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("api_key_name_ux")
                        .HasFilter("revoked_at is null");

                    b.ToTable("api_key", null, t =>
                        {
                            t.HasComment("Bearer keys with capability sets and an optional expiry. Lookup is by sha256(key).");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("app_setting_pkey");

                    b.ToTable("app_setting", null, t =>
                        {
                            t.HasComment("The admin knobs, one row per key. Only PUT /admin/settings/{key} changes a value. A missing row means the compiled default.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Beacon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active")
                        .HasComment("The one beacon whose updates fan out. At most one true (beacon_one_active). Zero is allowed.");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash")
                        .HasComment("sha256 of the plaintext key, 32 bytes. The plaintext is never stored.");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_prefix")
                        .HasComment("First 12 characters of the key, for display.");

                    b.Property<int>("KeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("key_version")
                        .HasComment("Incremented by rotate. Carried in the hub identity as \"<id>:<key_version>\"; the message path rejects a stale version.");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_heartbeat_at")
                        .HasComment("Last stored heartbeat.");

                    b.Property<DateTimeOffset?>("LastLocationAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_location_at")
                        .HasComment("Last stored location, published or not.");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at")
                        .HasComment("Any authenticated contact: REST call, hub authorize, hub message.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at")
                        .HasComment("Set once by revoke. A revoked beacon never authenticates again.");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role")
                        .HasComment("beacon or admin. Immutable after creation.");

                    b.Property<DateTimeOffset?>("StaleSince")
                        .HasColumnType("timestamptz")
                        .HasColumnName("stale_since")
                        .HasComment("Set by the stale-beacon chore; cleared by a heartbeat or a stored location.");

                    b.Property<JsonDocument>("Telemetry")
                        .HasColumnType("jsonb")
                        .HasColumnName("telemetry")
                        .HasComment("The last heartbeat body, stored as received.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("beacon_pkey");

                    b.HasAlternateKey("KeyHash")
                        .HasName("beacon_key_hash_key");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("beacon_one_active")
                        .HasFilter("is_active");

                    b.ToTable("beacon", null, t =>
                        {
                            t.HasComment("A trusted sender. Rows are never deleted; revoke is permanent.");

                            t.HasCheckConstraint("beacon_role_check", "role in ('beacon', 'admin')");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.BeaconEnrollmentToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("BeaconId")
                        .HasColumnType("bigint")
                        .HasColumnName("beacon_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("KeyCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("key_ciphertext")
                        .HasComment("AES-256-GCM of the plaintext beacon key (12-byte nonce prepended, 16-byte tag appended). Nulled when consumed.");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash")
                        .HasComment("sha256 of the wet_ token.");

                    b.HasKey("Id")
                        .HasName("beacon_enrollment_token_pkey");

                    b.HasAlternateKey("TokenHash")
                        .HasName("beacon_enrollment_token_token_hash_key");

                    b.ToTable("beacon_enrollment_token", null, t =>
                        {
                            t.HasComment("One-time tokens behind the enrollment QR code. 15-minute lifetime, single use.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.BeaconLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<long>("BeaconId")
                        .HasColumnType("bigint")
                        .HasColumnName("beacon_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id")
                        .HasName("beacon_log_pkey");

                    b.HasIndex("BeaconId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("beacon_log_beacon");

                    b.ToTable("beacon_log", null, t =>
                        {
                            t.HasComment("Red-Nose debug log uploads (admin-role beacons). Up to 2 MB each. 30-day retention.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.ContactMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_ip")
                        .HasComment("Client IP per the trusted-proxy rule; empty string for migrated rows.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("contact_message_pkey");

                    b.ToTable("contact_message", null, t =>
                        {
                            t.HasComment("Contact form submissions. No automatic retention; admins delete.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.ContentVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<JsonDocument>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document")
                        .HasComment("ContentDocument (contracts 1.3a) exactly as the snapshot embeds it: hidden rows omitted, canonical order.");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.PrimitiveCollection<Guid[]>("MediaIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("media_ids")
                        .HasDefaultValueSql("'{}'")
                        .HasComment("Every media_asset id the document references (MediaRef, media icons, background media). The orphan chore treats these as referenced while the row exists.");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_by");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256")
                        .HasComment("SHA-256 of the canonical bytes of document; POST /admin/content/publish answers 409 content_unchanged when the working set hashes to the newest row.");

                    b.HasKey("Id")
                        .HasName("content_version_pkey");

                    b.ToTable("content_version", null, t =>
                        {
                            t.HasComment("Published content documents. The row with the greatest id is what the snapshot carries; the newest 50 are kept, older rows are deleted in the publish transaction. Restore copies a row back into the working set and publishes nothing.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Cookie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CookieTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cookie_type_id");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("hidden_at")
                        .HasComment("Soft delete for moderation. Hidden cookies leave the tally but still count toward the per-person limit.");

                    b.Property<string>("HiddenBy")
                        .HasColumnType("text")
                        .HasColumnName("hidden_by");

                    b.Property<DateTimeOffset>("LeftAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("left_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note")
                        .HasComment("Never public. Visible to admins only.");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("cookie_pkey");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("cookie_person");

                    b.HasIndex("EventId", "CookieTypeId")
                        .HasDatabaseName("cookie_event_type_visible")
                        .HasFilter("hidden_at is null");

                    b.HasIndex("EventId", "PersonId")
                        .HasDatabaseName("cookie_event_person");

                    b.ToTable("cookie", null, t =>
                        {
                            t.HasComment("A cookie left by a registered person during a live event. No location.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.CookieType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Icon")
                        .HasColumnType("jsonb")
                        .HasColumnName("icon")
                        .HasComment("Icon value (contracts 1.3a): {\"source\":\"library\",\"id\":\"cookie\"} or {\"source\":\"media\",\"id\":\"<uuid of a ready svg media_asset>\"}; null until chosen.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("cookie_type_pkey");

                    b.ToTable("cookie_type", null, t =>
                        {
                            t.HasComment("Admin-managed. Locked (409 event_live) while any event has status 3. No delete; active = false removes a type from the snapshot.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at")
                        .HasComment("Stamped now() on every entry into status 4; admin-patchable.");

                    b.Property<JsonDocument>("FinalCookieTally")
                        .HasColumnType("jsonb")
                        .HasColumnName("final_cookie_tally");

                    b.Property<int>("FundsPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("funds_percent")
                        .HasComment("Cheer meter, 0 to 100.");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current")
                        .HasComment("The event the public site shows. Set only by POST /admin/events/{id}/current. At most one true (event_one_current).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("NextSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("next_seq")
                        .HasComment("Next location.seq for this event. Read and incremented under the row lock in the location transaction, so seq order is commit order.");

                    b.Property<long?>("RouteId")
                        .HasColumnType("bigint")
                        .HasColumnName("route_id")
                        .HasComment("Route shown for this event; null when unlinked.");

                    b.Property<Guid?>("RouteImageMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_image_media_id")
                        .HasComment("The route poster the site shows (contracts 1.3). A ready raster media_asset; svg and gif are refused at PATCH.");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scheduled_at")
                        .HasComment("Admin-entered. Required while status_id = 2.");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("status_id")
                        .HasComment("event_status.id. At most one row has 3 (event_one_live).");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("WentLiveAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("went_live_at")
                        .HasComment("Stamped now() on every entry into status 3; admin-patchable.");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("event_pkey");

                    b.HasAlternateKey("Year")
                        .HasName("event_year_key");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("event_one_current")
                        .HasFilter("is_current");

                    b.HasIndex("StatusId")
                        .IsUnique()
                        .HasDatabaseName("event_one_live")
                        .HasFilter("status_id = 3");

                    b.ToTable("event", null, t =>
                        {
                            t.HasComment("One row per flyover. Status changes only when an admin changes them.");

                            t.HasCheckConstraint("event_funds_percent_check", "funds_percent between 0 and 100");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.EventMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("EventTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("event_time")
                        .HasComment("The time the message is about, as entered by the admin. Display only.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("event_message_pkey");

                    b.HasIndex("EventId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("event_message_event_created");

                    b.ToTable("event_message", null, t =>
                        {
                            t.HasComment("Messages shown on the site. The snapshot carries the one with the greatest created_at (ties: greatest id).");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.EventStatus", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("event_status_pkey");

                    b.HasAlternateKey("Name")
                        .HasName("event_status_name_key");

                    b.ToTable("event_status", null, t =>
                        {
                            t.HasComment("Fixed lookup. Never edited through the API. Ids are the statusId values on every wire.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.EventStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<short?>("FromStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("from_status_id")
                        .HasComment("Null when there was no previous status.");

                    b.Property<short>("ToStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("to_status_id");

                    b.HasKey("Id")
                        .HasName("event_status_history_pkey");

                    b.HasIndex("EventId", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("event_status_history_event");

                    b.ToTable("event_status_history", null, t =>
                        {
                            t.HasComment("One row per status change, written in the status change transaction.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.IconLibraryState", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("LibrarySha256")
                        .HasColumnType("char(64)")
                        .HasColumnName("library_sha256");

                    b.Property<DateTimeOffset?>("WrittenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("written_at");

                    b.HasKey("Id")
                        .HasName("icon_library_state_pkey");

                    b.ToTable("icon_library_state", null, t =>
                        {
                            t.HasComment("Single row (id = 1). Hash of the icon library the fleet last wrote to the bucket. The boot migrator compares it with the compiled library and writes the icons when they differ (section 8.16).");

                            t.HasCheckConstraint("icon_library_state_id_check", "id = 1");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.LiveState", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("LastWriteAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_write_at");

                    b.Property<string>("LastWriteError")
                        .HasColumnType("text")
                        .HasColumnName("last_write_error");

                    b.Property<string>("LastWriteNode")
                        .HasColumnType("text")
                        .HasColumnName("last_write_node");

                    b.Property<long?>("LastWriteSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("last_write_seq");

                    b.Property<long?>("LastWriteVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("last_write_version");

                    b.HasKey("Id")
                        .HasName("live_state_pkey");

                    b.ToTable("live_state", null, t =>
                        {
                            t.HasComment("Single row (id = 1). Fleet-wide outcome of the last live-object write. Returned by GET /admin/live.");

                            t.HasCheckConstraint("live_state_id_check", "id = 1");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<double?>("AccuracyM")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_m");

                    b.Property<double?>("AltitudeM")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_m");

                    b.Property<long>("BeaconId")
                        .HasColumnType("bigint")
                        .HasColumnName("beacon_id");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<double?>("HeadingDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("heading_deg");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published")
                        .HasComment("beacon.is_active at the moment of the insert. Only published rows reach the live object.");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()")
                        .HasComment("When the API stored the row.");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at")
                        .HasComment("The fix time the beacon sent. Informational; it never decides anything.");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq")
                        .HasComment("Arrival order within the event, from event.next_seq. The only order that exists.");

                    b.Property<double?>("SpeedMps")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_mps");

                    b.HasKey("Id")
                        .HasName("location_pkey");

                    b.HasAlternateKey("EventId", "Seq")
                        .HasName("location_event_id_seq_key");

                    b.HasIndex("EventId", "Seq")
                        .IsDescending(false, true)
                        .HasDatabaseName("location_event_published_seq")
                        .HasFilter("published");

                    b.ToTable("location", null, t =>
                        {
                            t.HasComment("Every stored fix. Kept forever; exported by admins; never read by the public site.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Minted by the API (UUID v4) when the upload ticket is issued; it is the key segment media/{id}/.");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("alt");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind")
                        .HasComment("raster: png, jpeg, webp (variants derived). gif: stored as is. svg: validated, usable as an icon.");

                    b.Property<DateTimeOffset?>("OrphanedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("orphaned_at");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s3_key")
                        .HasComment("media/{id}/{filename}; the original bytes.");

                    b.Property<string>("Sha256")
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UnreferencedSince")
                        .HasColumnType("timestamptz")
                        .HasColumnName("unreferenced_since");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by");

                    b.Property<JsonDocument>("Variants")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("variants")
                        .HasDefaultValueSql("'{}'")
                        .HasComment("{ \"480\": \"media/{id}/w480.webp\", \"960\": ..., \"1600\": ... }: the WebP width variants that exist (raster only, widths below the source width).");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("media_asset_pkey");

                    b.HasAlternateKey("S3Key")
                        .HasName("media_asset_s3_key_key");

                    b.HasIndex("State", "CreatedAt")
                        .HasDatabaseName("media_asset_state_created");

                    b.ToTable("media_asset", null, t =>
                        {
                            t.HasComment("The media library. pending: ticket issued, bytes may or may not be in the bucket. ready: confirmed. orphaned: unreferenced for 30 days, objects tagged for lifecycle expiry; the row is deleted 8 days later.");

                            t.HasCheckConstraint("media_asset_kind_check", "kind in ('raster', 'svg', 'gif')");

                            t.HasCheckConstraint("media_asset_state_check", "state in ('pending', 'ready', 'orphaned')");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Outbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts")
                        .HasComment("Rows with 5 attempts stay unpublished and are visible in the logs.");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("claimed_at")
                        .HasComment("Set by the claim query; a claim older than 2 minutes is reclaimable.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("outbox_pkey");

                    b.HasIndex("Id")
                        .HasDatabaseName("outbox_unpublished")
                        .HasFilter("published_at is null");

                    b.ToTable("outbox", null, t =>
                        {
                            t.HasComment("Work for the leader chores, written in the same transaction as the change it announces. Topics: event.status_changed, event.message_posted, subscription.verify, contact.received.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Page", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<string>("NavLabel")
                        .HasColumnType("text")
                        .HasColumnName("nav_label")
                        .HasComment("Nav entry text; null keeps the page out of the nav. Always null on role pages.");

                    b.Property<int>("NavPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nav_position");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("role");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasComment("One lowercase path segment, ^[a-z0-9]+(-[a-z0-9]+)*$, 1 to 60; never auth, preview, api, admin, assets. Validated by the API.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("page_pkey");

                    b.HasAlternateKey("Slug")
                        .HasName("page_slug_key");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasDatabaseName("page_one_per_role")
                        .HasFilter("role <> 'none'");

                    b.ToTable("page", null, t =>
                        {
                            t.HasComment("Working set. The six role pages are seeded, undeletable, and role-immutable; none pages render at /<slug>. Hidden pages are omitted at publish.");

                            t.HasCheckConstraint("page_role_check", "role in ('none', 'no_event', 'planned', 'scheduled', 'live', 'ended', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CognitoSub")
                        .HasColumnType("uuid")
                        .HasColumnName("cognito_sub");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("person_pkey");

                    b.HasAlternateKey("CognitoSub")
                        .HasName("person_cognito_sub_key");

                    b.ToTable("person", null, t =>
                        {
                            t.HasComment("A registered person. Upserted on every authenticated request from the ID token (sub, email).");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.PreviewToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("preview_token_pkey");

                    b.HasAlternateKey("TokenHash")
                        .HasName("preview_token_token_hash_key");

                    b.ToTable("preview_token", null, t =>
                        {
                            t.HasComment("wpv_ tokens minted by POST /admin/content/preview-token, sha256 at rest, 15 minutes, reusable until expiry, deleted by the nightly cleanup 24 h after expiry. Database-backed so any node can answer GET /preview/document.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Route", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s3_key")
                        .HasComment("routes/{sha256}.json. Content-hashed, so an identical upload resolves to the existing row.");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256")
                        .HasComment("Lowercase hex SHA-256 of the canonical object bytes.");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by")
                        .HasComment("Admin email claim, or 'migration'.");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasComment("Absolute CDN URL of s3_key, carried into the snapshot as routeUrl.");

                    b.HasKey("Id")
                        .HasName("route_pkey");

                    b.HasAlternateKey("S3Key")
                        .HasName("route_s3_key_key");

                    b.ToTable("route", null, t =>
                        {
                            t.HasComment("Metadata for a route object on the CDN. The bytes live only in the bucket under s3_key; the row is never re-serialized from the database.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Section", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("data")
                        .HasDefaultValueSql("'{}'");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position")
                        .HasComment("Compacted to 0, 1, 2, ... within the page after every reorder, move, insert, and delete.");

                    b.Property<JsonDocument>("Presentation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("presentation")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("section_pkey");

                    b.HasIndex("PageId", "Position", "Id")
                        .HasDatabaseName("section_page_position");

                    b.ToTable("section", null, t =>
                        {
                            t.HasComment("Working set. kind names a registry entry (contracts 1.3a); data is validated against the kind schema, presentation against the shared presentation schema, at the draft level on write and at the publish level on publish.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.SectionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("data")
                        .HasDefaultValueSql("'{}'");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("section_item_pkey");

                    b.HasIndex("SectionId", "Position", "Id")
                        .HasDatabaseName("section_item_section_position");

                    b.ToTable("section_item", null, t =>
                        {
                            t.HasComment("Working set. Repeatable items of a section whose kind has an item schema (media, links, icon_row). position compacted like section.position.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.SiteSettingDraft", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("data")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("site_setting_draft_pkey");

                    b.ToTable("site_setting_draft", null, t =>
                        {
                            t.HasComment("Single row (id = 1). The site settings working set (contracts 1.3a SiteSettings), draft-validated on PUT, publish-validated on publish. Seeded from the starter content on first boot.");

                            t.HasCheckConstraint("site_setting_draft_id_check", "id = 1");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Snapshot", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BuiltAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("built_at");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s3_key");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Increments on every rebuild, including rebuilds that produce identical bytes. Nodes watch it on the reconcile tick.");

                    b.HasKey("Id")
                        .HasName("snapshot_pkey");

                    b.ToTable("snapshot", null, t =>
                        {
                            t.HasComment("Single row (id = 1). The current snapshot object. Rewritten in the same transaction as every snapshot-affecting write. Inserted by the first boot of an environment; absent means the environment has never finished booting.");

                            t.HasCheckConstraint("snapshot_id_check", "id = 1");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Sponsor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FbUrl")
                        .HasColumnType("text")
                        .HasColumnName("fb_url");

                    b.Property<string>("IgUrl")
                        .HasColumnType("text")
                        .HasColumnName("ig_url");

                    b.Property<Guid?>("LogoMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_media_id")
                        .HasComment("A ready media_asset chosen from the library; null when no logo. The API refuses to delete a referenced asset (409 media_in_use).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("sponsor_pkey");

                    b.HasIndex("LogoMediaId")
                        .HasDatabaseName("sponsor_logo_media")
                        .HasFilter("logo_media_id is not null");

                    b.ToTable("sponsor", null, t =>
                        {
                            t.HasComment("Sponsor master data. contact_person, email, phone, and address are admin-only and never reach the snapshot.");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.SponsorYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<decimal?>("AmountDonated")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_donated")
                        .HasComment("Admin-only. Drives lingerMs; never appears in a public object.");

                    b.Property<bool>("Anonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("anonymous");

                    b.Property<bool>("CanAdvertise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_advertise");

                    b.Property<int>("EventYear")
                        .HasColumnType("integer")
                        .HasColumnName("event_year");

                    b.Property<int?>("LingerMsOverride")
                        .HasColumnType("integer")
                        .HasColumnName("linger_ms_override")
                        .HasComment("0..600000, overrides the computed lingerMs for this year. Snapshot exposes only lingerMs; whether it was overridden is not revealed.");

                    b.Property<int?>("PinnedPosition")
                        .HasColumnType("integer")
                        .HasColumnName("pinned_position")
                        .HasComment("1..1000, pins the sponsor's slot for this year. Snapshot orders pinned rows first, pinned_position asc.");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint")
                        .HasColumnName("sponsor_id");

                    b.HasKey("Id")
                        .HasName("sponsor_year_pkey");

                    b.HasAlternateKey("SponsorId", "EventYear")
                        .HasName("sponsor_year_sponsor_id_event_year_key");

                    b.HasIndex("EventYear", "PinnedPosition")
                        .IsUnique()
                        .HasDatabaseName("sponsor_year_pinned_ux")
                        .HasFilter("pinned_position is not null");

                    b.ToTable("sponsor_year", null, t =>
                        {
                            t.HasComment("A sponsor's participation in one year. Upserted on (sponsor_id, event_year).");

                            t.HasCheckConstraint("sponsor_year_amount_donated_check", "amount_donated >= 0");

                            t.HasCheckConstraint("sponsor_year_linger_ms_override_check", "linger_ms_override is null or (linger_ms_override between 0 and 600000)");

                            t.HasCheckConstraint("sponsor_year_pinned_position_check", "pinned_position is null or (pinned_position between 1 and 1000)");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Subscriber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address")
                        .HasComment("Stored trimmed and lowercased.");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<string>("UnsubscribeToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unsubscribe_token")
                        .HasComment("Plaintext wsu_ token, stable for the life of the row.");

                    b.Property<DateTimeOffset?>("UnsubscribedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("unsubscribed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at");

                    b.Property<DateTimeOffset?>("VerifyExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verify_expires_at");

                    b.Property<byte[]>("VerifyTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("verify_token_hash")
                        .HasComment("sha256 of the last minted wsv_ token. Kept after verification until the next mint so the verify page is idempotent.");

                    b.HasKey("Id")
                        .HasName("subscriber_pkey");

                    b.HasAlternateKey("UnsubscribeToken")
                        .HasName("subscriber_unsubscribe_token_key");

                    b.HasAlternateKey("Channel", "Address")
                        .HasName("subscriber_channel_address_key");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("subscriber_person");

                    b.HasIndex("VerifyTokenHash")
                        .HasDatabaseName("subscriber_verify_token_hash")
                        .HasFilter("verify_token_hash is not null");

                    b.ToTable("subscriber", null, t =>
                        {
                            t.HasComment("Alert subscriptions. channel is email in v1; sms is reserved and rejected by the API.");

                            t.HasCheckConstraint("subscriber_channel_check", "channel in ('email', 'sms')");
                        });
                });

            modelBuilder.Entity("Wmsfo.Api.Data.AlertDelivery", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Outbox", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("alert_delivery_outbox_id_fkey");

                    b.HasOne("Wmsfo.Api.Data.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("alert_delivery_subscriber_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.BeaconEnrollmentToken", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Beacon", null)
                        .WithMany()
                        .HasForeignKey("BeaconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("beacon_enrollment_token_beacon_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.BeaconLog", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Beacon", null)
                        .WithMany()
                        .HasForeignKey("BeaconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("beacon_log_beacon_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Cookie", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.CookieType", null)
                        .WithMany()
                        .HasForeignKey("CookieTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("cookie_cookie_type_id_fkey");

                    b.HasOne("Wmsfo.Api.Data.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cookie_event_id_fkey");

                    b.HasOne("Wmsfo.Api.Data.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cookie_person_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Event", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("event_route_id_fkey");

                    b.HasOne("Wmsfo.Api.Data.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("RouteImageMediaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("event_route_image_media_id_fkey");

                    b.HasOne("Wmsfo.Api.Data.EventStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("event_status_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.EventMessage", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("event_message_event_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.EventStatusHistory", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("event_status_history_event_id_fkey");

                    b.HasOne("Wmsfo.Api.Data.EventStatus", null)
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("event_status_history_from_status_id_fkey");

                    b.HasOne("Wmsfo.Api.Data.EventStatus", null)
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("event_status_history_to_status_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Location", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Beacon", null)
                        .WithMany()
                        .HasForeignKey("BeaconId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("location_beacon_id_fkey");

                    b.HasOne("Wmsfo.Api.Data.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("location_event_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Section", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Page", null)
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("section_page_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.SectionItem", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("section_item_section_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Sponsor", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("LogoMediaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("sponsor_logo_media_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.SponsorYear", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Sponsor", null)
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sponsor_year_sponsor_id_fkey");
                });

            modelBuilder.Entity("Wmsfo.Api.Data.Subscriber", b =>
                {
                    b.HasOne("Wmsfo.Api.Data.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subscriber_person_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
