using System.Text.Json;

namespace Wmsfo.Api.Tests;

// A35 acceptance: every shared shape that the audit_log stamps carries `audit`.
// Reads the checked-in openapi.json (regenerated by the export) and asserts the
// property is present on each of the seventeen DTOs contracts 4.5 names.
public class AuditStampSchemaTests
{
    private static readonly string[] StampedShapes = new[]
    {
        "EventDto",
        "EventMessageDto",
        "RouteDto",
        "BeaconDto",
        "SponsorDto",
        "ApiKeyDto",
        "CookieTypeDto",
        "SubscriberAdminDto",
        "PersonDto",
        "ContactMessageDto",
        "SettingDto",
        "PageAdminDto",
        "SectionAdminDto",
        "SectionItemAdminDto",
        "MediaAssetDto",
        "ContentVersionInfoDto",
        "PreviewTokenDto",
    };

    [Fact]
    public void Every_stamped_shape_carries_audit()
    {
        var json = File.ReadAllText(ContractsPaths.OpenApiPath);
        using var doc = JsonDocument.Parse(json);
        var schemas = doc.RootElement.GetProperty("components").GetProperty("schemas");
        var missing = new List<string>();
        foreach (var name in StampedShapes)
        {
            if (!schemas.TryGetProperty(name, out var schema))
            {
                missing.Add(name + " (schema missing)");
                continue;
            }
            if (!schema.TryGetProperty("properties", out var props) ||
                !props.TryGetProperty("audit", out _))
            {
                missing.Add(name);
            }
        }
        Assert.True(missing.Count == 0,
            "shapes missing `audit` in the exported openapi: " + string.Join(", ", missing));
    }
}
